dependencies:
  - python=3.7
  - rasterio=1.1.0
  - geopandas=0.8.1
  - xarray=0.16.2
  - scipy=1.5.2
  - pip
  - pip:
      - citycatio==0.3.2
      - rioxarray==0.1.1
      - git+https://github.com/openhydrology/lmoments3.git@d2f30733275b4f4d7b4e86c13fd193733820c724