kind: Model
apiVersion: v1alpha3
metadata:
  displayName: CityCAT v5
  type: Modelling
  name: citycat
  summary: CityCAT is a tool for modelling, analysis and visualisation of surface water flooding.
  description: >
    CityCAT (City Catchment Analysis Tool) is a unique software tool for modelling, analysis and visualisation of
    surface water flooding. CityCAT enables rapid assessment of combined pluvial and fluvial flood risk and allows
    assessment of the effects of different flood alleviation measures.
spec:
  inputs:
    env:
      - name: RAIN
        title: Rainfall Total (mm)
        desc: The total amount of rainfall in one hour
        type: number
        default: 40
        min: 10
        max: 100

      - name: SIZE
        title: Domain Size (m)
        desc: The width and height of the domain to create
        type: integer
        default: 20
        min: 20
        max: 10000

    datasets:
      - uid: a11b62ac-e3bf-4989-87da-7da7dfa21de0
        versionUid: 0cec1aef-fe49-4c7d-9048-76caa7cb576d
        path: inputs/dem