name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: decrypt citycat
        run: gpg --batch --output citycat.exe --passphrase ${{ secrets.CITYCAT_PASSPHRASE }} --decrypt citycat.exe.gpg

      - name: build image
        run: docker build -t citycat-dafni .

      - name: test
        run: docker run -v $PWD/data:/data --env PYTHONUNBUFFERED=1 --env SIZE=0.1 --env DURATION=1 --env RETURN_PERIOD=100 --env X=258722 --env Y=665028 --env POOLING_RADIUS=10 --name citycat-dafni citycat-dafni
